/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2023-01-04 03:28:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.java.NewAgentJsp.Gender;
import org.glassfish.jersey.client.RequestEntityProcessing;
import com.java.NewAgentJsp.Agent;
import com.java.NewAgentJsp.AgentDaoImp;
import com.java.NewAgentJsp.AgentDAO;

public final class AddAgent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.java.NewAgentJsp.AgentDAO");
    _jspx_imports_classes.add("com.java.NewAgentJsp.Gender");
    _jspx_imports_classes.add("org.glassfish.jersey.client.RequestEntityProcessing");
    _jspx_imports_classes.add("com.java.NewAgentJsp.AgentDaoImp");
    _jspx_imports_classes.add("com.java.NewAgentJsp.Agent");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"AddAgent.jsp\" method=\"post\">\r\n");
      out.write("\tAgent Name:\r\n");
      out.write("\t<input type=\"text\" name=\"aname\"/><br/><br/>\r\n");
      out.write("\tCity :\r\n");
      out.write("\t<input type=\"text\" name=\"city\"><br/><br/>\r\n");
      out.write("\tGender :\r\n");
      out.write("\t <select name=\"gender\">\r\n");
      out.write("\t<option value=\"MALE\">MALE</option>\r\n");
      out.write("\t<option value=\"FEMALE\">FEMALE</option>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</select><br/><br/>\r\n");
      out.write("\tMaritalStatus :\r\n");
      out.write("\t<select name=\"mstatus\">\r\n");
      out.write("\t\t<option\tvalue=\"0\">0</option>\r\n");
      out.write("\t\t<option\tvalue=\"1\">1</option>\r\n");
      out.write("\t</select><br/><br/>\r\n");
      out.write("\t\r\n");
      out.write("\t <input type=\"number\" name=\"premium\">\r\n");
      out.write("\t<input type=\"submit\" value=\"Insert\"> \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</form>\r\n");
      out.write("\t");

		if(request.getParameter("premium")!=null)
		{
			
			AgentDAO dao = new AgentDaoImp();
			Agent agent= new Agent();
			agent.setName(request.getParameter("aname"));
			agent.setCity(request.getParameter("city"));
			agent.setGender(Gender.valueOf(request.getParameter("gender")));
			agent.setMaterialStatus(Integer.parseInt(request.getParameter("mstatus")));
			agent.setPremium(Integer.parseInt(request.getParameter("premium")));
			dao.addAgentDao(agent);
		
      out.write("\r\n");
      out.write("\t\t");
      if (true) {
        _jspx_page_context.forward("AgentShow.jsp");
        return;
      }
      out.write("\r\n");
      out.write("\t\t");
	
			
		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
